ci(lint): read python version without intermediate step

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -36,7 +36,7 @@ env:
   DRAW_DEPENDENCIES: "false"
 
   # Other "global" config
-  STATIC_ANALYSIS_PY: "3.10"
+  STATIC_ANALYSIS_PY: "3.8"
 
 jobs:
   # we use the below to read the workflow env vars and be able to use in "- if:" Job conditionals
@@ -519,52 +519,52 @@ jobs:
     strategy:
       matrix: ${{fromJSON(needs.set_github_outputs.outputs.matrix)}}
     steps:
-      - uses: actions/checkout@v3
+      # - uses: actions/checkout@v3
 
       - name: Read Pipe Parameter STATIC_ANALYSIS_PY, to determine Python runtime to use for Static Code Analysis
         run: echo "MY_STATIC_ANALYSIS_PY_VERSION=$STATIC_ANALYSIS_PY" >> $GITHUB_ENV  #  can be used in a with body of a next step in the Job, as eg: path: ${{ env.DIST_DIR }}
 
-      - name: Set up Python ${{ env.MY_STATIC_ANALYSIS_PY_VERSION }}
+      - name: Set up Python ${{ env.STATIC_ANALYSIS_PY }}
         uses: actions/setup-python@v4
         with:
-          python-version: ${{ env.MY_STATIC_ANALYSIS_PY_VERSION }}
+          python-version: ${{ env.STATIC_ANALYSIS_PY }}
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install tox==3.28 tox-gh-actions
+      # - name: Install dependencies
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     python -m pip install tox==3.28 tox-gh-actions
 
-      ## Isort, Black ##
-      - name: Lint check code with Isort and Black
-        if: ${{ matrix.platform != 'windows-latest' }}
-        run: tox -e lint -vv -s false
+      # ## Isort, Black ##
+      # - name: Lint check code with Isort and Black
+      #   if: ${{ matrix.platform != 'windows-latest' }}
+      #   run: tox -e lint -vv -s false
 
-      ## Pylint ##
-      - name: Run Pylint tool on Python Code Base
-        run: tox -e pylint -vv -s false | tee pylint-result.txt
+      # ## Pylint ##
+      # - name: Run Pylint tool on Python Code Base
+      #   run: tox -e pylint -vv -s false | tee pylint-result.txt
 
-      - name: Show Pylint output in Terminal
-        run: cat pylint-result.txt
+      # - name: Show Pylint output in Terminal
+      #   run: cat pylint-result.txt
 
-      - name: "Accept Code if Pylint Score > 8.2/10"
-        if: ${{ matrix.platform != 'windows-latest' }}
-        env:
-          PYLINT_THRESHOLD: 8.2
-        run: |
-          SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
-          echo "SCORE -> $SCORE"
-          # threshold check
-          if awk "BEGIN {exit !($SCORE >= $PYLINT_THRESHOLD)}"; then
-            echo "PyLint Passed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-          else
-            echo "PyLint Failed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-            exit 1
-          fi
+      # - name: "Accept Code if Pylint Score > 8.2/10"
+      #   if: ${{ matrix.platform != 'windows-latest' }}
+      #   env:
+      #     PYLINT_THRESHOLD: 8.2
+      #   run: |
+      #     SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
+      #     echo "SCORE -> $SCORE"
+      #     # threshold check
+      #     if awk "BEGIN {exit !($SCORE >= $PYLINT_THRESHOLD)}"; then
+      #       echo "PyLint Passed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
+      #     else
+      #       echo "PyLint Failed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
+      #       exit 1
+      #     fi
 
-      ## Pyflakes, Pyroma, McCabe, DodgyRun ##
-      - name: Check for errors, potential problems, convention violations and complexity, by running tools Pyflakes, Pyroma, McCabe, and DodgyRun
-        if: ${{ matrix.platform != 'windows-latest' }}
-        run: tox -e prospector -vv -s false
+      # ## Pyflakes, Pyroma, McCabe, DodgyRun ##
+      # - name: Check for errors, potential problems, convention violations and complexity, by running tools Pyflakes, Pyroma, McCabe, and DodgyRun
+      #   if: ${{ matrix.platform != 'windows-latest' }}
+      #   run: tox -e prospector -vv -s false
 
 
 # DRAW PYTHON DEPENDENCY GRAPHS
