ci(lint): static checks with isort, black, pylint, pyrom, pyflakes, mccabe, dodgy, profile-validator

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -21,10 +21,15 @@ on:
       - v*
 
 env:
+  ## Pipeline Constants ##
+
   # Job Matrix as an env var !
   FULL_MATRIX_STRATEGY: "{\"platform\": [\"ubuntu-latest\", \"macos-latest\", \"windows-latest\"], \"python-version\": [\"3.8\", \"3.9\", \"3.10\", \"3.11\"]}"
   UBUNTU_PY38_STRATEGY: "{\"platform\":[\"ubuntu-latest\"], \"python-version\":[\"3.8\"]}"
   TEST_STRATEGY: "{\"platform\":[\"ubuntu-latest\", \"macos-latest\", \"windows-latest\"], \"python-version\":[\"3.9\"]}"
+
+
+  ## Pipeline Parameters ##
 
   # On/Off switches for the various CI/CD steps
   # If false the step prevented from running
@@ -35,8 +40,14 @@ env:
   PUBLISH_ON_PYPI: "false"
   DRAW_DEPENDENCIES: "false"
 
-  # Other "global" config
-  STATIC_ANALYSIS_PY: "3.8"
+  ## Static Code Analysis Parameters ##
+  
+  # Python Runtime version to set the Job runner with
+  STATIC_ANALYSIS_PY: "3.10"
+
+  # Pylint Score Threshold, if the score is below this value the Job will fail
+  # If pylint rated our code below that score, the Job fails
+  PYLINT_SCORE_THRESHOLD: "8.2"
 
 jobs:
   # we use the below to read the workflow env vars and be able to use in "- if:" Job conditionals
@@ -510,16 +521,15 @@ jobs:
         docker logout
         echo "Published in Dockerhub :)"
 
+
 # STATIC CODE ANALYSIS & LINTING
   lint:
     name: "Static Code Analysis & Lint"
-    runs-on: ${{ matrix.platform }}
+    runs-on: ubuntu-latest
     needs: set_github_outputs
     if: ${{ needs.set_github_outputs.outputs.RUN_LINT == 'true' }}
-    strategy:
-      matrix: ${{fromJSON(needs.set_github_outputs.outputs.matrix)}}
     steps:
-      # - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
       - name: Read Pipe Parameter STATIC_ANALYSIS_PY, to determine Python runtime to use for Static Code Analysis
         run: echo "MY_STATIC_ANALYSIS_PY_VERSION=$STATIC_ANALYSIS_PY" >> $GITHUB_ENV  #  can be used in a with body of a next step in the Job, as eg: path: ${{ env.DIST_DIR }}
@@ -529,42 +539,45 @@ jobs:
         with:
           python-version: ${{ env.STATIC_ANALYSIS_PY }}
 
-      # - name: Install dependencies
-      #   run: |
-      #     python -m pip install --upgrade pip
-      #     python -m pip install tox==3.28 tox-gh-actions
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install tox==3.28
 
-      # ## Isort, Black ##
-      # - name: Lint check code with Isort and Black
-      #   if: ${{ matrix.platform != 'windows-latest' }}
-      #   run: tox -e lint -vv -s false
+      ## Isort ##
+      - name: "Isort\\: Require Semantic and Alphabetic order of the Python Imports"
+        if: ${{ matrix.platform != 'windows-latest' }}
+        run: tox -e isort -vv -s false
 
-      # ## Pylint ##
-      # - name: Run Pylint tool on Python Code Base
-      #   run: tox -e pylint -vv -s false | tee pylint-result.txt
+      ## Black ##
+      - name: "Black\\: Require Project Style to be followed by the Python Code"
+        if: ${{ matrix.platform != 'windows-latest' }}
+        run: tox -e black -vv -s false
 
-      # - name: Show Pylint output in Terminal
-      #   run: cat pylint-result.txt
+      ## Pylint ##
+      - name: Run Pylint tool on Python Code Base
+        run: TOXPYTHON="python${STATIC_ANALYSIS_PY}" tox -e pylint -vv -s false | tee pylint-result.txt
 
-      # - name: "Accept Code if Pylint Score > 8.2/10"
-      #   if: ${{ matrix.platform != 'windows-latest' }}
-      #   env:
-      #     PYLINT_THRESHOLD: 8.2
-      #   run: |
-      #     SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
-      #     echo "SCORE -> $SCORE"
-      #     # threshold check
-      #     if awk "BEGIN {exit !($SCORE >= $PYLINT_THRESHOLD)}"; then
-      #       echo "PyLint Passed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-      #     else
-      #       echo "PyLint Failed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-      #       exit 1
-      #     fi
+      - name: Show Pylint output in Terminal
+        run: cat pylint-result.txt
 
-      # ## Pyflakes, Pyroma, McCabe, DodgyRun ##
-      # - name: Check for errors, potential problems, convention violations and complexity, by running tools Pyflakes, Pyroma, McCabe, and DodgyRun
-      #   if: ${{ matrix.platform != 'windows-latest' }}
-      #   run: tox -e prospector -vv -s false
+      - name: "Accept Code if Pylint Score > 8.2/10"
+        if: ${{ matrix.platform != 'windows-latest' }}
+        run: |
+          SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
+          echo "SCORE -> $SCORE"
+          # threshold check
+          if awk "BEGIN {exit !($SCORE >= $PYLINT_SCORE_THRESHOLD)}"; then
+            echo "PyLint Passed! | Score: ${SCORE} out of 10 | Threshold: ${PYLINT_SCORE_THRESHOLD}"
+          else
+            echo "PyLint Failed! | Score: ${SCORE} out of 10 | Threshold: ${PYLINT_SCORE_THRESHOLD}"
+            exit 1
+          fi
+
+      ## Pyflakes, Pyroma, McCabe, DodgyRun, Profile Validator ##
+      - name: Check for errors, potential problems, convention violations and complexity, by running tools Pyflakes, Pyroma, McCabe, and DodgyRun
+        if: ${{ matrix.platform != 'windows-latest' }}
+        run: tox -e prospector -vv -s false
 
 
 # DRAW PYTHON DEPENDENCY GRAPHS
